[Variables]
WeatherCode=ROXX0003:1:RO
WeatherUnit=m
NetworkMaxUp=52428800
NetworkMaxDown=104857600
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":""
Substitute="January":"Ianuarie", "February":"Februarie", "March":"Martie", "April":"Aprilie", "May":"Mai", "June":"Iunie", "July":"Iulie", "August":"August", "September":"Septembrie", "October":"Octombrie", "November":"Noiembrie", "December":"Decembrie", "Monday":"Luni", "Tuesday":"Marti", "Wednesday":"Miercuri", "Thursday":"Joi", "Friday":"Vineri", "Saturday":"Sambata", "Sunday":"Duminica"
Helv=HelveticaNew
100=255,255,255,255
75=255,255,255,192
50=255,255,255,128
25=255,255,255,64
hide=255,255,255,0